default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: whitsonwedding_development

test:
  <<: *default
  database: whitsonwedding_test

production:
  <<: *default
  database: whitsonwedding_production
  username: whitsonwedding_rails
  password: <%= ENV['WHITSONWEDDING_RAILS_DATABASE_PASSWORD'] %>
